- test/run_tests
- test/src/test_slot.py
I think the test scripts could use a bit of refactoring, but this at least gives the user the ability to specify the launch command in situations where mpirun/mpiexec is not used.
> Add option to run_tests to allow user to specify job launch command

- CMakeLists.txt
- lua/CMakeLists.txt
- test/CMakeLists.txt
This creates configure-time dependency on all *.cc files, so when files are moved/renamed, `cmake` figures that out and re-configures the project automatically.
> No need to rerun cmake when files are renamed/moved/etc.

- test/run_tests
This PR adds a default behavior to the `run_tests` option `-d` to the directory that `run_tests` is located in. This allows the full regression test suite to be run without the `-d` option with `[python] test/run_tests`.
> Default directory choice for regression tests

- framework/mesh/mesh_continuum/mesh_continuum.cc
- lua/modules/linear_bolzmann_solvers/discrete_ordinates_solver/lbs_compute_leakage.cc
- lua/modules/linear_bolzmann_solvers/discrete_ordinates_solver/lbs_do_lua_utils.h
- modules/linear_boltzmann_solvers/a_lbs_solver/lbs_solver.cc
- modules/linear_boltzmann_solvers/a_lbs_solver/lbs_solver.h
- modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/lbs_discrete_ordinates_solver.cc
- modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/lbs_discrete_ordinates_solver.h
- test/modules/linear_boltzmann_solvers/transport_steady/tests.json
- test/modules/linear_boltzmann_solvers/transport_steady/transport_1d_leakage.lua
This PR adds more generalized routines for calculating leakages from boundaries. 
- Added the `ComputeLeakage` routine to `lbs::DiscreteOrdinatesSolver`. This routine takes a vector of boundary IDs and returns a map of boundary IDs to group-wise leakage values.
- Added the Lua wrapper function `lbs.ComputeLeakage`. The function takes a handle to the solver and optionally an array of boundary names (the standard ones used in OpenSn). The return value in Lua is a table of tables keyed with the boundary names and then the group indices.
- Added a simple leakage test, which gives the correct analytic solution.
- While the test is in parallel, the test does not rigorously test the communication carried out in the new routine. This would require a test where a a single boundary is shared among …
> Improved leakage calculations

- modules/linear_boltzmann_solvers/a_lbs_solver/lbs_solver.cc
This PR introduces the `reset_boundary_conditions` option in the `LBSSolver`. The flag simply clears the `boundary_preferences_` member, which results in all BCs becoming vacuum upon `InitializeBoundaries`. 
This flag is handled differently than other parameters. In order to support clearing and setting new boundary conditions, this flag is parsed before the loop over input parameters. By doing this, if the `reset_boundary_conditions` flag is passed with the `boundary_conditions` options, the existing boundary conditions will be cleared before setting the new ones, and not the other way around.
This feature is useful to solve multiple transport problems with varying boundary conditions, or, as will be seen in future PRs, in switching between forward and adjoint solves.
> Reset Boundary Conditions Option

- CMakeLists.txt
Also, build type is now an "enum", so when users use `ccmake` they can cycle through all build type by pressing Enter. No need to type the desired value (and possibly make a typo). This is a quality of life improvements.
Closes #84
> Default `CMAKE_BUILD_TYPE` is `Release`

- framework/physics/physics_material/multi_group_xs/adjoint_mgxs.cc
- framework/physics/physics_material/multi_group_xs/adjoint_mgxs.h
- framework/physics/physics_material/multi_group_xs/multi_group_xs.cc
- framework/physics/physics_material/multi_group_xs/multi_group_xs.h
- framework/physics/physics_material/multi_group_xs/single_state_mgxs.cc
- framework/physics/physics_material/multi_group_xs/single_state_mgxs.h
- lua/framework/physics/physics_material/multi_group_xs/multi_group_xs_lua_utils.cc
This PR introduces scaling factors for cross sections. Existing code capabilities does not store any information about the scalings that are applied. In effect, the `MakeCombined` routine is used to generate macroscopic cross sections that remain fixed throughout a simulation. Subsequent calls to `MakeCombined` compound the scaling factors, which is not the desired behavior when trying to change something like the density applied to a microscopic cross section. To obtain the correct behavior, a number of things were implemented:
- `scaling_factor_` member added to cross sections with accessor.
- `SetScalingFactor` multiplies cross sections by the ratio of the new scaling factor to the old and sets `scaling_factor_` to the new value.
- `MakeCombined` calls `SetScalingFactor` with the …
> XS Scaling Factors

- lua/modules/linear_bolzmann_solvers/lbs_solver/lbs_init_materials.cc
- modules/linear_boltzmann_solvers/a_lbs_solver/lbs_solver.cc
- modules/linear_boltzmann_solvers/a_lbs_solver/lbs_solver.h
- modules/linear_boltzmann_solvers/a_lbs_solver/lbs_structs.h
- modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/lbs_discrete_ordinates_solver.cc
- modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/lbs_discrete_ordinates_solver.h
- modules/linear_boltzmann_solvers/executors/lbs_steady_state.cc
- modules/mg_diffusion/mg_diffusion_solver.cc
- test/modules/linear_boltzmann_solvers/transport_adjoint/adjoint_2d_1b_adjoint.lua
- test/modules/linear_boltzmann_solvers/transport_adjoint/adjoint_2d_2b_adjoint.lua
- test/modules/linear_boltzmann_solvers/transport_adjoint/adjoint_2d_3b_adjoint.lua
This PR introduces an adjoint option into the `LBSSolver`. This is primarily done as a first step towards separating response evaluations from the actual solver. The adjoint option was added to the `Options` struct, and to `LBSSolver::InputParameters` as well as routines for reorienting angles.
- Within `InitializeMaterials` a check is performed to determine if adjoint mode is on or off. This dictates whether `matid_to_xs_map` gets set with `SingleStateMGXS` or `AdjointMGXS`.
- When the `adjoint` option is specified via `SetOptions`, the routine explicitly looks it before going through other parameters because it is order sensitive. 
- If the new flag is the same as the already set flag, nothing is done
- If the flags are different and a discretization is not present, the solver has not …
> Adjoint Option

- resources/configure_dependencies.py
If the directory name with extracted sources was all upper case, it was changed to lower case. This caused the build process to fail on case-sensitive file systems, since the build process honors the choice the package developers picked for the names of directories.
Closes #147
> Do not manipulate directory name with extracted sources in configure_dependencies.py

- framework/math/petsc_utils/petsc_utils.cc
- framework/math/petsc_utils/petsc_utils.h
- modules/linear_boltzmann_solvers/a_lbs_solver/acceleration/diffusion.cc
- test/framework/math/spatial_discretization/cg/sdm_test_01_continuous.cc
- test/framework/math/spatial_discretization/dg/sdm_test_01_discontinuous.cc
- test/framework/tutorials/fv_test1.cc
- test/framework/tutorials/fv_test2.cc
- test/framework/tutorials/pwlc_test1.cc
- test/framework/tutorials/pwlc_test2.cc
- test/modules/cfem_diffusion/c_diffusion_2d_3a_analytical_coef.lua
- test/modules/cfem_diffusion/c_diffusion_2d_3b_analytical_coef2.lua
- test/modules/cfem_diffusion/tests.json
- test/modules/dfem_diffusion/d_diffusion_2d_3a_analytical_coef.lua
- test/modules/dfem_diffusion/tests.json
- test/modules/linear_boltzmann_solvers/dsa/acceleration_diffusion_cfem.cc
- Removing RelativeResidualConvergenceTest
- Adjusting the relative tolerance in tests so that the residual drops below the expected "gold" value
Refs #102
> Removing custom relative convergence test

- framework/mesh/mesh_generator/split_file_mesh_generator.cc
- framework/mesh/mesh_generator/split_file_mesh_generator.h
- framework/runtime.cc
- framework/runtime.h
- lua/framework/lua_app.cc
- lua/framework/lua_app.h
- test/modules/linear_boltzmann_solvers/transport_steady/tests.json
This PR adds the input path to the openSn runtime as a `std::filesystem::path` object. This allows us to use the input path and filename stem throughout the code. In this case, I'm using the input filename stem as the default prefix for split mesh files. This prevents a whole host of issues when using the same filename prefix across multiple runs. IMHO, we should be using the input file stem for all files generated by the code instead of generic names that lack provenance.
This should fix the race condition encountered with the split file regression tests, and I have re-enabled the offending test.
There may already be a Lua method for grabbing the input file path from the command-line.  I'm not very familiar with Lua or the Lua interface yet. If such a method exists, I'm happy to use it …
> Adding input path to runtime. Changing default split mesh file prefix.

- modules/linear_boltzmann_solvers/a_lbs_solver/acceleration/nl_keigen_acc_residual_func.cc
- modules/linear_boltzmann_solvers/a_lbs_solver/iterative_methods/nl_keigen_ags_residual_func.cc
- modules/linear_boltzmann_solvers/a_lbs_solver/iterative_methods/power_iteration_keigen.cc
- modules/linear_boltzmann_solvers/a_lbs_solver/iterative_methods/power_iteration_keigen1.cc
- modules/linear_boltzmann_solvers/a_lbs_solver/iterative_methods/power_iteration_keigen2.cc
- modules/linear_boltzmann_solvers/a_lbs_solver/iterative_methods/wgs_context.cc
- modules/linear_boltzmann_solvers/a_lbs_solver/iterative_methods/wgs_linear_solver.cc
- modules/linear_boltzmann_solvers/a_lbs_solver/lbs_solver.cc
- modules/linear_boltzmann_solvers/a_lbs_solver/lbs_solver.h
- modules/linear_boltzmann_solvers/a_lbs_solver/lbs_structs.h
- modules/linear_boltzmann_solvers/a_lbs_solver/source_functions/source_function.cc
- modules/linear_boltzmann_solvers/a_lbs_solver/source_functions/source_function.h
- modules/linear_boltzmann_solvers/a_lbs_solver/source_functions/transient_source_function.cc
- modules/linear_boltzmann_solvers/a_lbs_solver/source_functions/transient_source_function.h
- modules/linear_boltzmann_solvers/b_diffusion_dfem_solver/lbs_mip_solver.cc
- modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/iterative_methods/sweep_wgs_context.cc
- modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/lbs_discrete_ordinates_solver.cc
- modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/aah_sweep_chunk.cc
- modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/aah_sweep_chunk.h
- modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/cbc_sweep_chunk.cc
- modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/cbc_sweep_chunk.h
- modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/sweep_chunk.h
- modules/linear_boltzmann_solvers/c_discrete_ordinates_adjoint_solver/lbs_adj_solver.cc
- modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/lbs_curvilinear_solver.cc
- modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.cc
- modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.h
- modules/linear_boltzmann_solvers/d_do_transient/lbts_transient_solver.cc
- modules/linear_boltzmann_solvers/executors/pi_keigen.cc
Implementation of cell-wise densities into the LBS framework. This change has the effect of the code "assuming" microscopic cross sections instead of macroscopic. This allows for more control over cross sections based on material states and flexibility in how the problem is defined. Of course, using a default density of one in all cells has the same effect as assuming a macroscopic cross sections.
- Added a density attribute that gets initialized to one in `LBSSolver` and associated getters.
- Hooked up densities to source functions for scaling scattering and fission sources.
- Hooked up densities to sweepers for scaling `sigma_t`.
- Read in and set cell-wise densities from files
- Include routines to set densities outside of the non-const getter.
> Cell-wise densities

- CMakeLists.txt
- doc/install_linux.md
- doc/install_macos.md
- resources/configure_dependencies.py
- test/modules/linear_boltzmann_solvers/transport_steady/tests.json
- test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1_poly_scotch.lua
This PR updates the PETSc install instructions to install the Scotch graph partitioner. It also adds Scotch to the PETSc install in configure_dependencies.py. I have tested the Scotch partitioner on multiple transport problems with no issues. 
Closes #50.
> Adding support for Scotch partitioner via PETSc

- framework/physics/physics_utils.cc
This fix allows the code to support PETSc versions 3.17.0 - 3.20.5. With versions of PETSc > 3.17.5, the following regression tests fail:
1. `tutorials/fv_test1.lua`
2. `tutorials/fv_test2.lua`
3. `tutorials/pwlc_test1.lua`
4. `tutorials/pwlc_test2.lua`
It looks to me like these tests are checking the residual value at a specific iteration number to determine pass/fail. That's probably not what we want to do.
> Minor fixes to support updated versions of PETSc.

- framework/math/linear_solver/linear_solver.h
This fixes a bug for a handful of regression tests that caused a segfault at the end of the problem run.
> Initializing several PETSc objects in LinearSolver class

- CMakeLists.txt
- cmake/OpenSnConfig.cmake.in
- lua/CMakeLists.txt
Implements `make install` to allow for use by external applications. Credit to @andrsd.
> Adding install target

- framework/utils/timer.cc
- lua/framework/lua_app.cc
- lua/framework/lua_app.h
- test/framework/post_processors/gold/solver_info_01.lua.gold
- test/framework/post_processors/gold/solver_info_02.lua.gold
- test/framework/post_processors/tests.json
- test/src/checks.py
- test/src/test_slot.py
This MR modifies the Lua app to always report the OpenSn version header, program start time, and program elapsed time. In addition, it modifies the regression test script to pull the elapsed time from the OpenSn output file for reporting purposes. This eliminates timing overhead introduced by Python, batch job systems, etc. I've also added a new parameter to the test script: `check_numlines`. This parameter defines the number of lines after `skiplines_top` to diff for regression purposes. This should make our regression testing a bit more robust... especially for console output.
> Use OpenSn elapsed time for regression test reporting

- test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly_balance_mg.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_2_unstructured.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_3_poly_quad_mod.lua
- test/modules/linear_boltzmann_solvers/transport_steady_cbc/transport_2d_1_poly.lua
A nil value was really passed into `aquad.OptimizeForPolarSymmetry` since there was a typo in the lua variable name.
> Pass correct handle into `aquad.OptimizeForPolarSymmetry`

- external/mpicpp-lite/impl/Group.h
This fixes the problem that OpenSn does not compile when using openmpi.
Closes #200
> Updating mpicpp-lite

- CMakeLists.txt
This allows users to build on older distros like Ubuntu 20.04
> Lower the lua version requirement to 5.3

- doc/install_linux.md
- doc/install_linux_easy.md
- doc/install_macos_easy.md
- resources/configure_dependencies.py
This PR updates the Linux install instructions and configure_dependencies.py script. I've made some simplifications to configure_dependencies.py to make the automated install less error prone (forcing the use of curl for downloads, removing march=native compiler flags, etc.). Both sets of instructions were successfully tested on a clean install of Ubuntu 22.04.4. 
This should partially address #87, but the MacOS installation instructions may still need updating.
I've testing the MacOS instructions and made slight modifications.
> Update Linux install instructions and configure_dependencies script

- .github/workflows/gh-pages.yml
`github-pages` workflow started to fail after #196 was merged. We don't test the workflow on PRs, so that slipped through the cracks.
> gha: adding caliper into gh-pages workflow dependencies

- external/cxxopts/cxxopts.h
- framework/utils/utils.cc
- framework/utils/utils.h
- lua/framework/interfaces/plugin.cc
- lua/framework/lua_app.cc
- lua/framework/lua_app.h
- test/framework/post_processors/gold/solver_info_01.lua.gold
- test/framework/post_processors/gold/solver_info_02.lua.gold
- test/framework/post_processors/tests.json
This PR refactors our CLI processing to use cxxopts. It should be much more robust and easier to maintain. I've divided the options into user-facing and a hidden developer-facing.  For example, `opensn -h` or `opensn --help` will display the user-facing options. `opensn --help-dev` will display developer-centric options.
This PR addresses #197.
> Using cxxopts package for cli.

- resources/configure_dependencies.py
I got a bit aggressive in my cleanup of configure_dependencies.py. The new version was causing some regression tests to fail. This PR fixes that issue. All regression tests now pass when using the dependencies installed by the configure_dependencies script.
> Fixing minor issues with configure_dependencies.py

- lua/framework/lua_app.cc
- test/src/test_slot.py
This PR removes all positional arguments from the CLI.  -i or --input is required for input files, and -l or --lua is required for Lua expressions. cxxopts allows specifying multiple options of the same type, so we only use the last option of each type found on the command line. We could probably flag that as an error if we want to.
Closes #213
> Removing positional arguments from CLI

- CMakeLists.txt
- lua/CMakeLists.txt
This PR changes CMakeLists.txt to link everything privately. An issue arose building an external application using OpenSn with dependencies built with conda. Privately linking everything fixed the problem. As far as I am aware, this change will necessitate external applications that use dependencies of OpenSn to also link to those libraries instead of those dependencies being available with OpenSn. This is not my area of expertise, so any feedback is welcomed.
> Private dependency linking

- CMakeLists.txt
- framework/materials/multi_group_xs/openmc_import.cc
- framework/utils/hdf_utils.h
- resources/configure_dependencies.py
This PR refactors the HDF utilities in `framework/utils/hdf_utils.h` to use the HDF C interface instead of the C++ interface. This simplifies our HDF installation and resolves potential issues with other dependencies. The C interface requires a bit more effort to ensure there are no resource leaks, but lsan gives us a clean bill of health for the OpenMC xs tests.
> Refactoring HDF utilities to use the HDF C interface instead of the C++ interface

- lua/framework/materials/multi_group_xs/multi_group_xs_lua_utils.cc
- lua/framework/materials/multi_group_xs/multi_group_xs_lua_utils.h
- test/modules/linear_boltzmann_solvers/transport_transient/transient_transport_1d_1.lua
- test/modules/linear_boltzmann_solvers/transport_transient/transient_transport_1d_2.lua
- test/modules/linear_boltzmann_solvers/transport_transient/transient_transport_1d_3.lua
- test/modules/linear_boltzmann_solvers/transport_transient/transient_transport_2d_2.lua
- test/modules/linear_boltzmann_solvers/transport_transient/transient_transport_2d_3.lua
This PR introduces a Lua API for setting cross section scaling factors. In order to do this before, one had to call `new_xs_handle = xs.MakeCombined({{ xs_handle, factor }})`. By construction, this routine sets the scaling factor for `xs_handle` to `factor` and then sets `new_xs_handle` to the scaled `xs_handle` with a scaling factor of 1. This is convoluted and unintuitive.
The new API routines make this process intuitive. A user can now either create a new XS object by scaling another with `macro_xs = xs.MakeScaled(micro_xs, factor)` or set the scaling factor in an existing XS object with `xs.SetScalingFactor(macro_xs, factor)` in Lua.
> XS Scaling Factors API

- framework/mesh/cell/cell.cc
- test/framework/data_types/data_types_test_00.cc
PR #230 fixed a bug in ByteArray that uncovered another bug in our cell serialization. gcc reports this as:
```
opensn/framework/data_types/byte_array.h:88:16: warning: ‘void* memcpy(void*, const void*, size_t)’ 
writing to an object of type ‘struct opensn::Vector3’ with no trivial copy-assignment; use copy-assignment
or copy-initialization instead [-Wclass-memaccess]
```
But the real problem is that we are attempting to serialize non-POD types.  We should absolutely avoid this. We need to move to a proper serialization library and not write our own routines. In this case, we were serializing `Vector3`, so it's a relatively simple change to deal with each of the individual data members separately.
> Do not serialize non-POD types

- framework/materials/isotropic_multigroup_source.h
- framework/materials/scalar_value.h
- lua/framework/materials/lua_material.cc
- modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
- modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.h
- modules/linear_boltzmann_solvers/lbs_solver/lbs_structs.h
- modules/linear_boltzmann_solvers/lbs_solver/source_functions/source_function.cc
- modules/mg_diffusion/mg_diffusion_solver.cc
- modules/mg_diffusion/mg_diffusion_solver.h
This simple PR just spells out "Group" in `IsotropicMultiGrpSource` and renames the header file.
> IsotropicMultiGrpSource -> IsotropicMultiGroupSource

- CMakeLists.txt
This PR adds functionality to CMakeLists.txt to always generate a JSON compile commands database for use with various tools.
> Generate JSON compile commands database

- framework/math/math_vector_nx.h
- framework/mesh/mesh_vector.h
- lua/framework/materials/lua_material.cc
- lua/framework/materials/lua_material.h
- test/modules/linear_boltzmann_solvers/transport_steady/reed_balance.lua
This PR is a follow-up to #257 that continues the Lua materials interface refactor.
- Removes `mat.AddProperty` from the Lua interface
- Eliminates material property name options within `mat.SetProperty`
- Only allows one property of a given type per material
Closes #252
> Materials Lua Interface Refactor

- test/modules/cfem_diffusion/c_diffusion_2d_1a_linear.lua
- test/modules/dfem_diffusion/d_diffusion_2d_1a_linear.lua
- test/modules/linear_boltzmann_solvers/mg_diffusion_steady/mip_diffusion_3d_1b_ortho.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_1d_1.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly_balance.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly_balance_mg.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_2_unstructured.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_3_poly_quad_mod.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_5_poly_a_ani_hetero_bndry.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1_poly_parmetis.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1_poly_qmom_part1.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1_poly_qmom_part2.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1a_extruder.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1b_ortho.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_2_unstructured.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_4_cycles_1.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_5_cycles_2.lua
- test/modules/linear_boltzmann_solvers/transport_steady_cbc/transport_1d_1.lua
- test/modules/linear_boltzmann_solvers/transport_steady_cbc/transport_2d_1_poly.lua
An initial version of the changes in PR #261 changed the export function for lines and slices to `Export()` from `ExportPython()`.  All of the respective inputs were also changed to reflect this renaming. In response to reviewer comments, these names were later changed to `ExportToCSV` for lines and `ExportToPython` for slices. However, the inputs were never updated to reflect this change.  This PR fixes that oversight.
> Fixing field function export calls for lines and slices

- framework/runtime.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/lbs_discrete_ordinates_solver.cc
- modules/linear_boltzmann_solvers/lbs_solver/groupset/lbs_groupset.cc
- modules/linear_boltzmann_solvers/lbs_solver/groupset/lbs_groupset.h
Debugging this issue led to some minor cleanup in lbs_groupset. One problem being that not all of the lbs_groupset member variables were properly initialized. It also led to a small fix in runtime::Finalize().
> Fixing a minor memory issue in the discrete ordinates solver destructor

- modules/linear_boltzmann_solvers/lbs_solver/groupset/lbs_groupset.cc
- test/modules/linear_boltzmann_solvers/transport_steady_cbc/tests.json
The GMRES restart parameter specified in groupset options was never assigned to the corresponding member variable, leading to the solver always using the default value of 30.
> Groupset solver doesn't honor GMRES restart parameter

- framework/materials/multi_group_xs/openmc_import.cc
- test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_3d_openmcxs_U235.lua
- test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_3d_openmcxs_UO2.lua
- test/modules/linear_boltzmann_solvers/transport_keigen/tests.json
The transfer and production matrices read from OpenMC were transposed. This was discovered when running a source-driven problem. The test suite will be made more robust by adding such a test (in a subsequent PR).
The absorption XS should not be read from OpenMC as it is prone to statistical noise (i.e., total is not exactly equal to absorption + outscatter). It is better to just read total and transfer from OpenMC and compute ourselves absoprtion from that.
> fixing transfer and production matrices when reading them for openmc

- lua/framework/lua_app.cc
This PR updates the processing order of cli options so that verbosity is set before processing any other options (except help options).  This fixes a bug where `--dump-object-registry` wasn't honoring the verbosity level.
> Updating processing order of cli options

- framework/mesh/io/gmsh_io.cc
- framework/mesh/io/obj_io.cc
- framework/mesh/io/vtk_io.cc
- framework/mesh/mesh.h
- framework/mesh/mesh_continuum/mesh_continuum.cc
- framework/mesh/mesh_continuum/mesh_continuum.h
- framework/mesh/mesh_generator/extruder_mesh_generator.cc
- framework/mesh/mesh_generator/mesh_generator.cc
- framework/mesh/mesh_generator/split_file_mesh_generator.cc
- framework/mesh/mesh_generator/split_file_mesh_generator.h
- framework/mesh/unpartitioned_mesh/unpartitioned_mesh.cc
- framework/mesh/unpartitioned_mesh/unpartitioned_mesh.h
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/lbs_discrete_ordinates_solver.cc
- MeshAttributes are not bit-wise flags
- Removing trailing underscores from public member variables in SplitMeshInfo
- Creating setters according to code standards in `UnpartitionedMesh`
Closes #286
> MeshAttributes are no longer bit-wise flags

- framework/runtime.cc
- framework/runtime.h
- lua/framework/lua_app.cc
To avoid clashes, renaming the global variable `name` to a static variable named `program`. Please suggest alternatives if you have other ideas.
> Changing global variable `name`

- framework/data_types/ndarray.h
- framework/math/statistics/cdfsampler.cc
- framework/math/statistics/cdfsampler.h
- framework/mesh/io/gmsh_io.cc
- framework/mesh/io/obj_io.cc
- framework/mesh/io/vtk_io.cc
- framework/mesh/mesh_face.h
- framework/mesh/mesh_generator/extruder_mesh_generator.cc
- framework/mesh/mesh_generator/mesh_generator.cc
- framework/mesh/mesh_generator/orthogonal_mesh_generator.cc
- framework/mesh/surface_mesh/surface_mesh.cc
- framework/mesh/surface_mesh/surface_mesh.h
- framework/mesh/unpartitioned_mesh/unpartitioned_mesh.cc
- framework/mesh/unpartitioned_mesh/unpartitioned_mesh.h
- lua/framework/math/quadratures/sldfesq/create_sldfesq_quadrature.cc
- lua/framework/mesh/field_function_interpolation/ffinterpol_create.cc
- lua/framework/mesh/surface_mesh/surface_mesh.cc
- Use `make_shared` in `CreateSLDFESQAngularQuadrature`
- Use `make_shared` in `FFInterpolationCreate`
- Use `make_shared` in `MeshSurfaceMeshCreate`
- `LightWeightCell`s in `UnpartitionedMesh` are `shared_ptr`s
- `sub_intvls` in `CDFSampler::SubIntvl` are `shared_ptr`s
- `sub_intvls` in `CDFSampler::SubIntvl` are `shared_ptr`s
- Using `shared_ptr`s in `CopyUGridCellsAndPoints`
- Using `shared_ptr`s in `SurfaceMesh`
- Use `std::vector` instead of C-style arrays in `SurfaceMesh`
- Use `std::vector` instead of C-style arrays in `NDArray`
Closes #95
> Removing naked pointers in favor of `std::shared_ptr`

- .github/workflows/builds.yaml
- .github/workflows/regression.yaml
- .github/workflows/weekly.yaml
Github workflows have migrated to node20 for actions. node20 does not work on older OS's like our CI machine. Trying to force node16 to get things working again. 
Update: It looks like forcing node16 works... for now. Hopefully Github leaves it be for a while.
> Forcing the use of node16 for regressions workflow.

- resources/configure_dependencies.py
This PR updates configure_dependencies.py to use PETSc 3.20.6 and includes other minor changes to successfully build on macOS 14.5+.
> Updating configure_dependencies.py to PETSc 3.20.6

- modules/linear_boltzmann_solvers/discrete_ordinates_solver/lbs_discrete_ordinates_solver.cc
- modules/linear_boltzmann_solvers/executors/pi_keigen.cc
- modules/linear_boltzmann_solvers/executors/pi_keigen_scdsa.cc
- modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
This PR fixes multiple issues with multi-groupset k-eigenvalue problems with reflecting boundaries. The default k-eigenvalue solver was incorrectly setting active sources for only the first groupset. In addition, angular flux storage for reflecting boundaries was not sized properly for the current implementation (the implementation can be improved, but that is beyond the scope of this PR).  Resolves issue #321.
> Bug fixes for multi-groupset, k-eigenvalue problems with reflecting boundaries

- framework/field_functions/field_function.cc
- framework/field_functions/field_function.h
- framework/field_functions/field_function_grid_based.cc
- framework/field_functions/field_function_grid_based.h
- framework/field_functions/field_function_interface.cc
- framework/field_functions/interpolation/ffinter_line.cc
- lua/framework/physics/field_function/physics_get_field_func_list.cc
- modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
- test/framework/tutorials/tutorial_91a_pwld.cc
- test/framework/tutorials/tutorial_93_raytracing.cc
This PR adds constructors and input options to make the default behavior of `FieldFunctionGridBased` default to a finite volume representation. The `discretization` input parameter is now defaulted to "FV" and constructors which require a grid instead of a discretization. 
Due to a lack of coordinate system information on the mesh, this currently only works for Cartesian grids. This will be changed with the resolution of #330.
> Removed discretization requirement for `FieldFunctionGridBased`

- test/modules/linear_boltzmann_solvers/transport_steady/transport_1d_1.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_1d_3a_dsa_ortho.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_2_unstructured.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_3_poly_quad_mod.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_4a_dsa_ortho.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_4b_dsa_ortho.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_3a_dsa_ortho.lua
- test/modules/linear_boltzmann_solvers/transport_steady_cbc/transport_1d_1.lua
- test/modules/linear_boltzmann_solvers/transport_steady_cbc/transport_2d_1_poly.lua
The default behavior of the AGS solver has changed, and we now attempt a pointwise convergence of the groupset-to-groupset scattering. The previous behavior was to only do 1 AGS iteration. For a handful of our regression tests, pointwise AGS convergence is not necessary (doesn't change the answer we are testing for) and significantly increases the run time. For those tests, this PR sets the number of AGS iterations to 1.
> Forcing some multi-groupset tests to use only 1 AGS iteration

- lua/modules/linear_bolzmann_solvers/lbs_solver/lbs_common_lua_functions.h
- lua/modules/linear_bolzmann_solvers/lbs_solver/lbs_get_field_funcs.cc
There was no simple way to access the power field function that can be turned on in LBS solver within Lua. This PR adds the Lua routine `lbs.GetPowerFieldFunction` which either returns the appropriate field function handle or throws an error if the option to create the power field function is turned off.
> Routine to access power field function from Lua

- framework/math/math.cc
- framework/math/math.h
- modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/ags_solver.cc
- modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/ags_solver.h
- modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/classic_richardson.cc
- modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/classic_richardson.h
- modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/convergence.cc
- modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/convergence.h
- modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
- modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.h
- modules/linear_boltzmann_solvers/lbs_solver/lbs_structs.h
- test/modules/linear_boltzmann_solvers/transport_steady/tests.json
This PR changes the default convergence check for the AGS solver from a pointwise check on phi to a check on the L2 norm of the error in phi. This mirrors the behavior of the old PETSc AGS solver and brings some consistency to convergence checking across the WGS and AGS solvers. Using a pointwise convergence check for AGS is optional, and will be used by the Classic Richardson WGS solver since it also uses a pointwise convergence check.
> Adding L2-convergence check to the AGS iterative solver

- modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
Fixes a typo in precursors accessors.
Closes #374
> Precursors accessor bug fix

- .github/workflows/builds.yaml
This PR updates the nightly sanitizer build to exclude implicit conversion checks. It also adds correct use of the lsan suppressions file. This should get nightly build tests back on track and help us better track compilation issues with the different supported compilers. 
I've opened an issue for the implicit conversion and divide-by-zero bugs that need to be fixed (#378).
> Updating sanitizer build.

- framework/mesh/mesh_generator/distributed_mesh_generator.cc
- framework/mesh/mesh_generator/distributed_mesh_generator.h
- test/modules/linear_boltzmann_solvers/transport_steady/tests.json
- test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_6a_dist_mesh.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_6b_dist_mesh.lua
This PR adds support for MPI-distributed meshes. Rank 0 builds and partitions the mesh and sends each piece of the mesh to the appropriate rank via MPI.  Tested out to ~27,000 ranks with various mesh types. 2.5X to 4X faster than our split mesh capability at that scale.
This probably needs to be our standard mesh generator, but I'm leaving it as an option until we have gained some experience using it.
I believe this resolves #20.
> Adding support for MPI-distributed meshes.

- framework/math/linear_solver/linear_solver.cc
- framework/math/linear_solver/linear_solver.h
- modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/wgs_linear_solver.cc
This PR cleans up the use of PETSc iterative method names and fixes an issue in `WGSLinearSolver` where we were checking for the wrong name. This PR also restricts the use of the PETSc name to the `LinearSolver `class.
> Cleaning up use of PETSc iterative method names

- modules/linear_boltzmann_solvers/discrete_ordinates_adjoint_solver/lbs_adj_solver.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/lbs_discrete_ordinates_solver.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep_chunks/sweep_chunk.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep_chunks/sweep_chunk.h
- modules/linear_boltzmann_solvers/lbs_solver/io/flux_moments_io.cc
- modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/nl_keigen_ags_solver.cc
- modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/wgs_context.cc
- modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
- test/modules/linear_boltzmann_solvers/transport_steady/tests.json
The routine `SweepChunk::ZeroDestinationPhi` which gets called within `SweepScheduler::ZeroFluxDataStructures` which gets called within `SweepWGSContext::ApplyInverseTransportOperator` zeros the entire `destination_phi` vector (set to `LBSSolver::phi_new_local_`). This is a problem because sweep chunks operate on groupsets and flux moments vector  is defined over all groups. For single groupset problems, this does not pose an issue, but for multiple groupset problems, it means that with the standard machinery of groupset scoped copying `phi_new_local_` at the end of a solve will be zero for all groupsets other than the last groupset. As a result, the AGS solver actually converges only on the last groupset instead of the full flux moments vector. This PR rewrites the …
> Sweep chunk zeroing bug

- modules/linear_boltzmann_solvers/diffusion_dfem_solver/iterative_methods/mip_wgs_context.cc
- modules/linear_boltzmann_solvers/diffusion_dfem_solver/iterative_methods/mip_wgs_context.h
- modules/linear_boltzmann_solvers/diffusion_dfem_solver/lbs_mip_solver.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/iterative_methods/sweep_wgs_context.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/iterative_methods/sweep_wgs_context.h
- modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/wgs_context.h
The existing `WGSContext` stores a reference to an `LBSSolver`. The derived classes store this and a reference to the derived class (`DiffusionDFEMSolver` or `DiscreteOrdinatesSolver`). This seems redundant and unnecessary. Instead, storing an `std::shared_ptr<LBSSolver>` and casting where necessary seems more reasonable. This PR implements this.
One test fails: `test/framework/tutorials/tutorial_93_raytracing.lua`. The test segfaults during the call to `Finalize` and I cannot figure out why. Any advice on what the issue is would be much appreciated!
> WGS Context Cleanup

- modules/linear_boltzmann_solvers/diffusion_dfem_solver/iterative_methods/mip_wgs_context.cc
- modules/linear_boltzmann_solvers/diffusion_dfem_solver/iterative_methods/mip_wgs_context.h
- modules/linear_boltzmann_solvers/diffusion_dfem_solver/lbs_mip_solver.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/iterative_methods/sweep_wgs_context.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/iterative_methods/sweep_wgs_context.h
- modules/linear_boltzmann_solvers/executors/pi_keigen_scdsa.cc
- modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/wgs_context.h
- test/modules/linear_boltzmann_solvers/transport_keigen/c5g7/c5g7.lua
- test/modules/linear_boltzmann_solvers/transport_steady/tests.json
- test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1_poly_qmom_part1.lua
- Only do a post-solve sweep for Krylov methods, excluding one-sweep PETSc Richardson.
- Only do a single sweep within the SCDSA eigenvalue acceleration method.
Update (11/12/2024):
After trying to find a bug with @wdhawkins for some time, we concluded that the failing test was just a bad test. `transport_3d_1_poly_qmom_part1.lua` did one sweep, wrote the source moments to file, and then printed field function operation results on an unconverged solution. Without the additional sweep, this changes the values printed in the `part1` test because it was unconverged. The change in sweep behavior changed the behavior in `part2` slightly because it changed what was written to the source moments files. The `part1` test was changed to check for completion only because the values are meaningless. …
> Extra Sweeps Fix

- modules/linear_boltzmann_solvers/discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/fluds/aah_fluds_common_data.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/spds/aah.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/spds/cbc.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/spds/spds.h
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/sweep.h
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep_chunks/aah_sweep_chunk.cc
This PR simplifies the SPLS implementation and creates a levelized version of SPLS. The levelized version is necessary to enable parallelism along the sweep front. Although not included in this PR, I have implemented and tested a levelized version of the AAH sweepchunk and all regression tests pass.
**Note that this PR changes our sweep ordering.**
> Simplifying SPLS implementation. Creating levelized SPLS.

- framework/data_types/ndarray.h
- framework/mesh/mesh_continuum/mesh_continuum.cc
- framework/mesh/mesh_continuum/mesh_continuum.h
With these fixes, I think we'll have clean builds across all of our supported compilers.
> Fix GCC compiler warnings for MeshContinuum and NDArray classes

- framework/math/math.cc
- framework/math/math.h
- modules/linear_boltzmann_solvers/discrete_ordinates_adjoint_solver/lbs_adjoint.cc
Functions are renamed as:
- Vec1Norm -> L1Norm
- Vec2Norm -> L2Norm
- VecInfinityNorm -> LInfNorm
- VecPNorm -> LpNorm
Closes #351
> Refactoring API for computing norms

- framework/mesh/mesh_generator/mesh_generator.cc
- framework/mesh/mesh_generator/mesh_generator.h
This PR adds a simple partition rebalancing algorithm that allows the code to continue execution if the partitioner creates partitions with zero cells. The algorithm computes the average number of cells per partition and moves cell from heavier partitions to the partition with zero cells. This algorithm is a last resort as it will likely destroy the spatial locality of the partitioning.
See issue #409.
> Simple partition rebalancing

- .github/workflows/builds.yaml
- .github/workflows/regression.yaml
- .github/workflows/weekly.yaml
Allows us to easily update compiler minor versions without needing to modify our workflows for the self-hosted runners.
> Use compiler major version number for module names on self-hosted runners

- framework/mesh/cell/cell.h
- framework/mesh/logical_volume/logical_volume.h
This PR corrects a small number of circular header dependencies in the code base as identified by `clang-tidy`. Partially address #462 as I don't believe this will find re-inclusions.
`clang-tidy` can be used to analyze headers and identify true circular dependencies. An example invocation is below:
```
run-clang-tidy -checks='-*,misc-header-include-cycle' -p build -extra-arg=-I/opt/local/opensn/clang/19.1.5/mpich-4.3.0b1/include
```
> Fixing circular dependencies in header files

- modules/linear_boltzmann_solvers/lbs_solver/lbs_vecops.cc
- modules/linear_boltzmann_solvers/lbs_solver/lbs_vecops.h
Moves `GroupsetScopedCopy()` into `lbs_vecops.cc` and removes `lbs_solver.h` from `lbs_vecops.h`. This resolves issue #458, but is a workaround ahead of refactoring `modules/linear_boltzmann_solvers`.
> Moving `GroupsetScopedCopy()` into `lbs_vecops.cc`

- CMakeLists.txt
This PR adds CUDA support to our CMake configuration. It has been tested with both a cuBLAS sweep kernel and a custom CUDA sweep kernel. 
This PR also bumps our required CMake version to 3.18. This is necessary to enable auto detection of the CUDA compute architecture. How well it works is questionable, but it's better than nothing. The architecture can also be set via the command line if auto detection fails.
I'm definitely not a CMake expert, so suggestions to improve this are appreciated.
> Adding CUDA support to CMake

- framework/mesh/mesh_continuum/mesh_continuum.cc
- framework/mesh/mesh_continuum/mesh_continuum.h
- test/unit/framework/mesh/mesh_continuum_test.cc
https://github.com/Open-Sn/opensn/pull/261 broke `CheckPointInsideCell` for polyhedra. Before the refactoring, if a single tetrahedron was found that contains the point, it was considered contained (see [here](https://github.com/wdhawkins/openSn/blob/fb1e7b055d910577acc437c0c71acb34704b186b/framework/mesh/mesh_continuum/mesh_continuum.cc#L975) for old version). After the refactoring, the point needed to be contained within _all_ tetrahedra. This corrects that issue.
Impressively, this bug didn't break anything. This probably needs unit tests.
> Refactor `CheckPointInsideCell` and fix for polyhedra

- modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
This PR fixes a small issue where we incorrectly appended extensions to empty restart file names. This resulted in attempts to read restart files that did not exist.
> Don't append extensions to empty restart file names

- framework/mesh/mesh_continuum/mesh_continuum.cc
- framework/mesh/mesh_continuum/mesh_continuum.h
- framework/mesh/mesh_mapping/mesh_mapping.cc
- framework/mesh/mesh_mapping/mesh_mapping.h
- framework/mesh/mesh_vector.h
- test/unit/framework/mesh/mesh_continuum_test.cc
- test/unit/framework/mesh/mesh_mapping_test.cc
- test/unit/framework/mesh/vector3_test.cc
- test/unit/opensn_unit_test.cc
- test/unit/opensn_unit_test.h
Adds the start for mapping between a fine and a coarse mesh for acceleration. I'm attempting to do this in pieces instead of one big PR, testing pieces at a time.
- Still serial only. Eventually, the fine mesh will be allowed to be parallel. The coarse mesh will remain serial (still need a way to do this).
- The execution of this isn't what it will be when actually used in production. Waiting on https://github.com/Open-Sn/opensn/pull/435 to be able to input multiple mesh generators. Another object will instantiate and execute this in the future. 
- The naming might be awful. `MeshMapping` might be confusing when compared with the discretization and `GetCellMapping`.
Adding comments for parts I have questions on / want specific feedback on.
> Add `MeshMapping` for future separate mesh acceleration

- .github/workflows/builds.yaml
- .github/workflows/regression.yaml
- .github/workflows/weekly.yaml
- CMakePresets.json
Clang's source-based coverage seems to have an issue with shared object libraries, so I've modified the CMake coverage preset to use gcov and switched to GCC to prevent any version discrepancies. I've added the coverage workflow and Coveralls integration to the nightly build tests for the time being. If everything goes smoothly, we can move them to the regression workflow or wherever we would like.
If the coverage workflow runs smoothly for a couple of nights, I'll add the badge to the main page.
Here's a link to the first coverage report: https://coveralls.io/builds/72376782
> Adding coverage workflow and Coveralls integration to nightly builds

- framework/math/functions/function.h
- framework/math/functions/scalar_material_function.h
- framework/math/functions/scalar_spatial_function.h
- framework/math/functions/scalar_spatial_material_function.h
- framework/math/functions/vector_spatial_function.h
- framework/math/functions/vector_spatial_material_function.h
- framework/math/quadratures/angular/curvilinear_product_quadrature.h
In this PR:
- Destructor of [`CurvilinearQuadrature`](https://github.com/Open-Sn/opensn/issues/509) is made public.
- Default constructor to `Function` classes (`ScalarMaterialFunction`, `ScalarSpatialFunction`, `ScalarSpatialMaterialFunction`, `VectorSpatialFunction`, `VectorSpatialMaterialFunction`), paving the way for binding these classes with Python.
Closes #509
> Public destructor for CurvilinearQuadrature and default constructor for Function

- CMakeLists.txt
This was accidently removed by 8d4caf8a9ebf0a98706b4d4fd5404544d728ab62
This fixes the OpenSn build on systems where `boost` is located in non-standard location.
> Bring back `find_package(Boost)`

- lua/lib/opensn.cc
- modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
- modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.h
Originally, this API was returning a Lua handle. Now, it returns a pointer to the `FieldFunctionGridBased` class.
refs #506
> Bringing back `GetPowerFieldFunction`

- doc/CMakeLists.txt
Moving testing/tutorials into separate Lua and Python directories inadvertently broke generation of documentation for tutorials.  This PR fixes this issue. Note that we only generation tutorial documents for the Lua interface right now.
> Fixing documentation generation for tutorials.

- .github/workflows/builds.yaml
- .github/workflows/gh-pages.yml
- .github/workflows/regression.yaml
- .github/workflows/weekly.yaml
1. Bump actions version to v4 across the board.
2.  Standardize on GCC 14 for all tests that use GCC.
3.  Add Python testing.
4. Fixes test directory argument to test script to account for splitting tests into Lua and Python directories.
> Workflow updates

- CMakeLists.txt
> Fixing `make test` to correctly execute either Lua or Python tests.

- CMakeLists.txt
- test/CMakeLists.txt
We now look for a system gtest and link against that instead of building gtest locally and then linking against that. If a system gtest is not found, gtest is built locally and then linked against. This is in response to Issue #554.
> Modified the CMakeLists.txt file in the main dir and the test dir.

- doc/pyapi/index.rst
- pyopensn/py_env.cc
- python/lib/functor.h
- python/lib/math.cc
In this PR, Python binding for `ScalarSpatialFunction` is added.
> Add Python binding for ScalarSpatialFunction

- python/lib/console.cc
- test/python/framework/post_processors/solver_info_01.py
- test/python/framework/post_processors/solver_info_02.py
- test/python/modules/linear_boltzmann_solvers/transport_keigen/c5g7/c5g7.py
- test/src/job_manager.py
- test/src/test_slot.py
- tools/developer/lsan.supp
1. Updating Python post processor tests to ensure consistent output across platforms.
2. Resolving a stack-use-after-scope issue in the Python binding of MPIBarrier.
3. Updating LSAN suppressions for Python.
4. Increasing the job wait time in the regression testing script to improve reliability.
5. Updating large C5G7 inputs to correctly set number of sweeps for SCDSA and SMM methods.
> Python testing updates

- pyopensn/py_env.cc
Removes extraneous ANSI escape codes from output when running with the Python module. This fixes the issue with failing regression tests when testing with the Python module (all tests in `transport_steady`, `transport_adjoint`, `transport_keigen`, `transport_steady_cyl`, and `transport_steady_cbc` pass with the module).
> Suppressing colorized log output when using the Python module

- framework/runtime.cc
- framework/runtime.h
- test/lua/framework/tutorials/tutorial_93_raytracing.lua
- test/lua/modules/linear_boltzmann_solvers/dsa/acceleration_diffusion_cfem.lua
- test/lua/modules/linear_boltzmann_solvers/dsa/acceleration_diffusion_dfem.lua
This PR restore the function stack that was accidentally removed in PR 574. It also modifies Lua tests to use SetOrthogonalBoundaries instead of SetupOrthogonalBoundaries.
> Restoring function stack for the Lua interface and update Lua inputs

- CMakeLists.txt
Header only installs of Boost don't include `BoostConfig.cmake`. Since many installs are header-only, fall back to using the `FindBoost` module if `find_package(Boost CONFIG)` fails.
> Falling back to module mode if find_package(Boost CONFIG) fails

- .github/workflows/builds.yaml
- test/src/test_slot.py
This PR temporarily removes tutorials from our sanitizer workflow until our CI Python install supports sanitizers.
> Temporarily removing tutorials from sanitizer workflow

- doc/CMakeLists.txt
- tutorials/python/mesh/index.rst
this should fix the doc not building. I changed the notebook file name to be lowercase vtu and the cmakelist was not changed appropriately. sorry, it was not caught during the review process and i suppose that trying to build the doc is not part of testing
> typo in filename broke the doco build

- CMakeLists.txt
- lua/CMakeLists.txt
- Lua is a dependency, so needs to be included and linked publicly, so the depending apps do not have to bother with discovering, including, and linking the libs. We really want to use the header location and libs we built OpenSn against
- Also, install LuaBridge so that OpenSn-based apps can register/bind their new classes
> Fixing install target for lua

- framework/mesh/io/gmsh_io_v22.cc
- framework/mesh/io/gmsh_io_v41.cc
- modules/linear_boltzmann_solvers/lbs_problem/lbs_problem.cc
- test/python/modules/linear_boltzmann_solvers/transport_steady/transport_2d_gmsh_v2.py
- test/python/modules/linear_boltzmann_solvers/transport_steady/transport_2d_gmsh_v4.py
- test/python/modules/linear_boltzmann_solvers/transport_steady/transport_3d_gmsh_v2.py
- test/python/modules/linear_boltzmann_solvers/transport_steady/transport_3d_gmsh_v4.py
The current behavior for OpenSn is to remap Gmsh physical region ids so that block ids always starts at 0. For example, a Gmsh mesh with physical regions 1 and 2 will have those regions remapped to block ids 0 and 1. This PR removes this remapping so that block ids correspond to the original Gmsh physical region tags.
> Removing block id remapping for Gmsh meshes

- modules/linear_boltzmann_solvers/lbs_problem/volumetric_source/volumetric_source.cc
- modules/linear_boltzmann_solvers/lbs_problem/volumetric_source/volumetric_source.h
This PR brings a bit of sanity to volumetric source logging. Because we don't provide volumetric source instances with a user-supplied id, this patch enumerates instances so we can provide useful per source definition statistics to the user. In addition, per-rank stats now require verbosity level 1.
> Improving volumetric source logging.

- framework/mesh/mesh_continuum/mesh_continuum.cc
- framework/mesh/mesh_continuum/mesh_continuum.h
- python/lib/mesh.cc
- test/python/framework/mesh/tests.json
- test/python/framework/mesh/volume_per_material.py
returning the volume per blockID in python
usage is:
```
volumes_per_block = grid.ComputeVolumePerBlockID()
for block_id, volume in volumes_per_block.items():
print(f"Block {block_id}: volume = {volume:.6e}")
```
> returning the volume per blockID in python

- lua/lib/console.cc
- test/lua/framework/parameters/tests.json
This gets nightly tests back on track.
> Updating parameter tests to reflect changes in Lua error formatting.

- doc/install/easy_install.rst
- doc/install/install.rst
- setup.py
This PR adds `nbconvert` to install dependencies.
When regression tests are needed, OpenSn must be installed using ``pip install .[dev]``.
> Add nbconvert to requirement

- framework/math/quadratures/angular/curvilinear_product_quadrature.cc
- framework/math/quadratures/angular/curvilinear_product_quadrature.h
- modules/linear_boltzmann_solvers/discrete_ordinates_curvilinear_problem/sweep_chunks/aah_sweep_chunk_rz.cc
- python/lib/aquad.cc
- python/lib/py_app.cc
- python/lib/py_wrappers.h
Renames CurvilinearQuadrature to CurvilinearProductQuadrature and derives it from ProductQuadrature.  Partially addresses #658.
> Updates to CurvilinearQuadrature

- framework/materials/multi_group_xs/multi_group_xs.h
- framework/materials/multi_group_xs/openmc_import.cc
- framework/materials/multi_group_xs/opensn_import.cc
- framework/materials/multi_group_xs/xsfile.cc
- framework/materials/multi_group_xs/xsfile.h
- framework/utils/utils.h
- python/lib/xs.cc
- test/python/framework/tutorials/tutorial_06_wdd.cc
- test/python/framework/tutorials/tutorial_91a_pwld.cc
This:
- introduces `XSFile` class which has the cross-section file reading logic
- removes `MultiGroupXS::Initialize` and replaces it with `MultiGroupXS::LoadFromOpenSn` which better matches the python API
- all "business" logic is inside `MultiGroupXS::LoadFromOpenSn` where we read from `XSFile` and then process the data
Closes #218
> Refactoring opensn native cross-section file reader in its own class

- modules/linear_boltzmann_solvers/lbs_problem/lbs_problem.cc
1) It is a virtual method
2) It is called from `Initialize`, so no need to have it called twice.
Closes #740
> Don't call `InitializeBoundaries` from a ctor

- modules/linear_boltzmann_solvers/lbs_problem/lbs_problem.cc
- modules/linear_boltzmann_solvers/lbs_problem/lbs_problem.h
- python/lib/py_wrappers.h
- python/lib/solver.cc
- test/python/framework/tutorials/tutorial_93_raytracing.py
- test/python/modules/linear_boltzmann_solvers/transport_adjoint/response_2d_1.py
- test/python/modules/linear_boltzmann_solvers/transport_adjoint/response_2d_2.py
- test/python/modules/linear_boltzmann_solvers/transport_adjoint/response_2d_3.py
- test/python/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_3d_2g_exo_pyramid.py
- test/python/modules/linear_boltzmann_solvers/transport_steady/wrong_parameter_type.py
This PR adds the methods setting/clearing sources and boundary conditions methods to Python interface.
Note: boundary conditions and sources arguments in ``OptionBlock`` to be removed (with regression tests to be updated).
> Add set/clear sources and boundary conditions methods to Python interface

- CMakeLists.txt
- python/CMakeLists.txt
This restores the functionality that was accidently removed by #760. If the target name is `libNAME` then cmake creates a `liblibNAME` file. Thus, we need to set the correct file name via the OUPUT_NAME property.
> cmake: correcting file names for the opensn library files

- .github/workflows/builds.yaml
Deprecating GCC 9.5 due to lack of c++20 support. Adding Clang 19.
> Update compiler matrix for builds workflow

- external/caribou/cuda/event.hpp
- external/caribou/cuda/stream.hpp
- modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep_chunks/aah_sweep_chunk.cu
In this PR, Event is implemented for the external library `caribou`.
Notable changes:
- `cudaEvent` wrapper is implemented, including:
* create with flag
* query
* synchronize
* time-measurement
* create interprocess handle (for copying across multiple MPI ranks)
* convert interprocess handle back to event.
- `cudaStream` wrapper implementation is expanded, notably:
* query
* synchronize
* record event
* wait for event
* add asynchronous callback to the stream (pure host function to be executed in the stream)
> Add Event for caribou

- modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep/angle_aggregation/angle_aggregation.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep/communicators/aah_async_comm.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep/fluds/aah_fluds.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep/fluds/aah_fluds.h
- modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep/fluds/cbc_fluds.h
- modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep/fluds/fluds.h
In this PR, references to `std::vector<double>` are replaced with the non-owning view `std::span<double>`.
This change prepares the codebase for supporting non-standard containers for angular flux data, such as GPU host vectors.
> Convert FLUDS vector references into std::span

- .github/workflows/builds.yaml
Adds CUDA builds for GCC and Clang to nightly builds workflow. Regression tests coming soon.
> Adding CUDA target to builds workflow
