- framework/post_processors/PostProcessor.cc
See https://stackoverflow.com/q/9225567/6122323 for details
Closes #13
> Fixing printf format string

- doc/YReGenerateDocumentation.sh
- framework/runtime.cc
- test/src/test_slot.py
> Command line arguments are kebab-style

- test/run_tests
- test/src/jobmanager.py
- Removing unused variable
- Fixing infinite loop when a single test with a dependency is specified
- Check existence of a test dependency
> Improving run_tests script

- CMakeLists.txt
- Print message where VTK was found and which version.
- Improving VTK detection. If very old version was found, report that as an error.
Closes #77
> Report if VTK was found

- doc/install_linux.md
- doc/start_developer_tutorials.md
- doc/start_install.md
- doc/start_source_code_doc.md
- doc/start_user_tutorials.md
I must have missed quite a few in the previous PR. I apologize. I think a single reviewer is enough for this one!
> removing old naming

- resources/configure_dependencies.py
- functions are defined before any code happens
- errors are indicated by exceptions
- script stops on first error encountered rather then trying to continue from a incorrect state (i.e. do not try to compile if configure step failed)
- all packages are installed into install dir unix style, i.e. header files go to `${INSTALL}/include`, libs go to `${INSTALL}/lib`, etc.
- logs are now in `${INSTALL}/logs`
- sources are unpacked and compiled from `${INSTALL}/src`
- `PETSC_ROOT` is changed to `PETSC_DIR`
- User is informed about setting `CMAKE_PREFIX_PATH` which is needed for successful cmake build of OpenSn
- Fixed typos
- script for setting env vars is called `set_opensn_env.sh` and is located in `${INSTALL}/bin`
> Improving `configure_dependencies.py`

- modules/linear_boltzmann_solvers/a_lbs_solver/acceleration/diffusion_mip_solver.cc
- modules/linear_boltzmann_solvers/a_lbs_solver/acceleration/diffusion_pwlc_solver.cc
- modules/linear_boltzmann_solvers/a_lbs_solver/lbs_solver.cc
- modules/linear_boltzmann_solvers/a_lbs_solver/lbs_structs.h
- modules/linear_boltzmann_solvers/a_lbs_solver/point_source/point_source.cc
- modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/lbs_discrete_ordinates_solver.cc
- modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/aah_sweep_chunk.cc
- modules/linear_boltzmann_solvers/b_discrete_ordinates_solver/sweep_chunks/cbc_sweep_chunk.cc
- modules/linear_boltzmann_solvers/c_discrete_ordinates_adjoint_solver/lbs_adj_solver.cc
- modules/linear_boltzmann_solvers/c_discrete_ordinates_curvilinear_solver/sweep_chunks/lbs_curvilinear_sweep_chunk_pwl.cc
A quick PR to make the unit cell matrices have intuitive names.
Closes #73
> Renamed Unit Cell Matrices

- framework/mesh/mesh_continuum/mesh_continuum.cc
- framework/mesh/surface_mesh/surface_mesh.cc
- framework/mesh/unpartitioned_mesh/unpartitioned_mesh.cc
- lua/framework/logging/log.cc
- lua/framework/utils/lua_exit.cc
Removing some left-over references to ChiTech
> Removing references to ChiTech

- doc/coding_standard.md
- doc/index.rst
Collected information from issue #3.
Closes #3
> Adding coding standard page into doco

- lua/framework/mesh/field_function_interpolation/ffinterpol_create.cc
- lua/framework/mesh/field_function_interpolation/ffinterpol_get_value.cc
- lua/framework/mesh/field_function_interpolation/ffinterpol_set_property.cc
- lua/framework/mesh/logical_volume/logic_volume_lua.cc
- lua/modules/linear_bolzmann_solvers/lbs_solver/lbs_group_set_ops.cc
- lua/modules/linear_bolzmann_solvers/lbs_solver/lbs_set_property.cc
Continuation of macro clean up work.
> Clean up of short-hand macros

- doc/scripts/lua2md.py
> Allow optional space between -- and ]] when parsing lua files with doco

- doc/CMakeLists.txt
> Properly detect and use python interpreter in the doco generation

- framework/field_functions/field_function_grid_based.cc
- framework/mesh/mesh_continuum/mesh_continuum.cc
> Fixing file export in parallel

- doc/coding_standard.md
> Updating coding standards with #include rules

- CMakeLists.txt
- test/run_tests
- test/src/test_slot.py
Run tests by typing `make test` in the build dir
> Adding test target that runs the tests in a basic setup

- test/framework/math/spatial_discretization/cg/tests.json
- test/framework/math/spatial_discretization/dg/tests.json
- test/framework/tutorials/tests.json
- test/modules/cfem_diffusion/tests.json
- test/modules/dfem_diffusion/tests.json
- test/modules/linear_boltzmann_solvers/dsa/tests.json
- test/modules/linear_boltzmann_solvers/mg_diffusion_keigen/tests.json
- test/modules/linear_boltzmann_solvers/mg_diffusion_steady/tests.json
- test/modules/linear_boltzmann_solvers/transport_adjoint/tests.json
- test/modules/linear_boltzmann_solvers/transport_keigen/c5g7/tests.json
- test/modules/linear_boltzmann_solvers/transport_keigen/tests.json
- test/modules/linear_boltzmann_solvers/transport_steady/tests.json
- test/modules/linear_boltzmann_solvers/transport_steady_cbc/tests.json
- test/modules/linear_boltzmann_solvers/transport_steady_cyl/tests.json
- test/src/checks.py
- KeyValuePairCheck can specify `abs_tol` and `rel_tol`
- FloatCompareCheck can specify `abs_tol` and `rel_tol`
- Updating tests
Refs #165
> Checks in tests can specify `abs_tol` and `rel_tol`

- framework/math/petsc_utils/petsc_utils.cc
- framework/math/petsc_utils/petsc_utils.h
- modules/cfem_diffusion/cfem_diffusion_solver.cc
- modules/dfem_diffusion/dfem_diffusion_solver.cc
- modules/fv_diffusion/fv_diffusion_solver.cc
- modules/mg_diffusion/mg_diffusion_solver.cc
- test/framework/math/spatial_discretization/cg/sdm_test_01_continuous.cc
- test/framework/math/spatial_discretization/dg/sdm_test_01_discontinuous.cc
- test/framework/tutorials/fv_test1.cc
- test/framework/tutorials/fv_test2.cc
- test/framework/tutorials/pwlc_test1.cc
- test/framework/tutorials/pwlc_test2.cc
> CreateCommonKrylovSolverSetup can specify `abs_tol` and `rel_tol`

- test/framework/math/spatial_discretization/cg/sdm_test_01_continuous.cc
- test/framework/math/spatial_discretization/cg/tests.json
- test/framework/math/spatial_discretization/dg/sdm_test_01_discontinuous.cc
- test/framework/math/spatial_discretization/dg/tests.json
- test/framework/tutorials/fv_test1.cc
- test/framework/tutorials/fv_test2.cc
- test/framework/tutorials/pwlc_test1.cc
- test/framework/tutorials/pwlc_test2.cc
- test/framework/tutorials/tests.json
- Reducing the number of maximum allowed iterations
- Checking that the solve converged via a prescribed tolerance. If so,
we print "Converged" into the log and we check that via a StrCompare check
Closes #165
> Improving tests

- test/src/test_slot.py
Fixing regression introduced by #176
> Print only file name in test results

- test/modules/linear_boltzmann_solvers/dsa/tests.json
rather than a number of iteration to achieve convergence
Refs #165
> Updating tests to check convergence and solution norm

- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/communicators/aah_async_comm.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/communicators/aah_async_comm.h
This PR is a more in-depth refactoring of the AAH sweep communicator, including some minor fixes. No significant change in performance is expected, but the implementation is simpler and streamlined.
> More in-depth refactoring of AAH sweep communicator

- doc/start_install.md
- tutorials/lbs/first/first_example.lua
- tutorials/old/basic_diffusion_simulation.md
> Updating tutorials to reflect the new CLI interface

- framework/utils/utils.h
Fixes error with GCC 13.x reported in #220.
> Fixes for GCC 13.x

- modules/linear_boltzmann_solvers/discrete_ordinates_solver/iterative_methods/sweep_wgs_context.cc
- modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
This small PR makes a few very small changes that make the output more readable when multiple transport runs are performed and boundary conditions are modified.
> Small modifications

- framework/mesh/mesh_generator/mesh_generator.cc
Throw an error instead of crashing if we generate a partition with zero cells. This can easily happen if we have more ranks than cells. For us to exit gracefully in this case, it's necessary to have every location calculate min/max/avg cells per partition and throw if min is zero.
> Throw an exception if we generate a partition with zero cells

- external/mpicpp-lite/impl/Communicator.h
- external/mpicpp-lite/impl/Datatype.h
- external/mpicpp-lite/impl/Enums.h
- external/mpicpp-lite/impl/Environment.h
- external/mpicpp-lite/impl/Error.h
- external/mpicpp-lite/impl/Group.h
- external/mpicpp-lite/impl/Operation.h
- external/mpicpp-lite/impl/Request.h
- external/mpicpp-lite/impl/Status.h
- external/mpicpp-lite/impl/Test.h
- external/mpicpp-lite/impl/Wait.h
- external/mpicpp-lite/mpicpp-lite.h
> Updating mpicpp-lite

- tools/README.md
- tools/developer/lsan.supp
- tools/xs/OpenMC_Create_MGXS_Library.ipynb
- tools/xs/create_openmc_xslib.ipynb
Adding `tools` directory.  This initial commit includes:
`developer/lsan.supp`: lsan suppressions file
`xs/OpenMC_Create_MGXS_Library.ipynb`: Jupyter notebook for creating OpenMC cross-section libraries
> Initial commit of tools directory

- framework/math/quadratures/angular/sldfe_sq_quadrature.cc
> Removing custom typedef in `sldfe_sq.cc`

- modules/linear_boltzmann_solvers/discrete_ordinates_solver/lbs_discrete_ordinates_solver.cc
- test/modules/linear_boltzmann_solvers/transport_steady/reed_balance.lua
- test/modules/linear_boltzmann_solvers/transport_steady/tests.json
The Reed problem with a balance printout is added to the regression tests
> adding reed problem with balance checks

- framework/object_factory.h
- framework/post_processors/post_processor_printer.cc
- framework/utils/utils.h
- lua/framework/console/console.h
- Removing duplicate definitions
- Adding `OpenSn` prefix to avoid name collisions
- Improving doco
Closes #249
> Refactoring `JoinWords` macros

- framework/mesh/mesh_generator/orthogonal_mesh_generator.cc
- framework/mesh/mesh_generator/orthogonal_mesh_generator.h
- modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
- test/modules/linear_boltzmann_solvers/mg_diffusion_keigen/keigenvalue_mip_2d_1a_qblock.lua
- test/modules/linear_boltzmann_solvers/mg_diffusion_keigen/keigenvalue_mip_2d_1b_qblock.lua
- test/modules/linear_boltzmann_solvers/transport_keigen/c5g7/c5g7.lua
- test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_2d_1a_qblock.lua
- test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_2d_1a_qblock_cbc.lua
- test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_2d_1b_qblock.lua
- test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_2d_1b_qblock_cbc.lua
- test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_2d_1c_qblock.lua
- test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_2d_1c_qblock_cbc.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly_balance_mg.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_2_unstructured.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_3_poly_quad_mod.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_4b_dsa_ortho.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_5_poly_a_ani_hetero_bndry.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1_poly_parmetis.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1_poly_scotch.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1a_extruder.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_1b_ortho.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_2_unstructured.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_4_cycles_1.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_6a_split_mesh.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_6b_split_mesh.lua
- test/modules/linear_boltzmann_solvers/transport_steady_cbc/transport_1d_1.lua
- test/modules/linear_boltzmann_solvers/transport_steady_cbc/transport_2d_1_poly.lua
- test/modules/linear_boltzmann_solvers/transport_steady_cyl/transport_2d_cyl_1_monoenergetic.lua
- test/modules/linear_boltzmann_solvers/transport_steady_cyl/transport_2d_cyl_2_multigroup.lua
> Changing boundary ID to boundary name mapping in orthogonal mesh generator

- .editorconfig
- .flake8
- .github/workflows/qa.yaml
- .gitignore
- doc/scripts/lua2md.py
- resources/clang-format-hook.py
- resources/configure_a_module.py
- resources/configure_dependencies.py
- test/src/__init__.py
- test/src/checks.py
- test/src/jobmanager.py
- test/src/test_slot.py
- Fixing exception handling
- Adding workflow for python linting
- Python files are flake8 clean
> Adding Python linting

- modules/linear_boltzmann_solvers/executors/lbs_steady_state.cc
- modules/linear_boltzmann_solvers/executors/nl_keigen.cc
- modules/linear_boltzmann_solvers/executors/nl_keigen.h
- modules/linear_boltzmann_solvers/executors/pi_keigen.cc
- modules/linear_boltzmann_solvers/executors/pi_keigen.h
- modules/linear_boltzmann_solvers/executors/pi_keigen_scdsa.cc
- modules/linear_boltzmann_solvers/executors/pi_keigen_scdsa.h
- test/modules/linear_boltzmann_solvers/mg_diffusion_keigen/keigenvalue_mip_1d_1g.lua
- test/modules/linear_boltzmann_solvers/mg_diffusion_keigen/keigenvalue_mip_2d_1a_qblock.lua
- test/modules/linear_boltzmann_solvers/mg_diffusion_keigen/keigenvalue_mip_2d_1b_qblock.lua
- test/modules/linear_boltzmann_solvers/transport_keigen/c5g7/c5g7.lua
- test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_1d_1g.lua
- test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_1d_1g_cbc.lua
- test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_2d_1a_qblock.lua
- test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_2d_1a_qblock_cbc.lua
- test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_2d_1b_qblock.lua
- test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_2d_1b_qblock_cbc.lua
- test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_2d_1c_qblock.lua
- test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_2d_1c_qblock_cbc.lua
- test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_3d_openmcxs.lua
- test/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_3d_openmcxs_cset.lua
This PR performs minor cleanup and refactoring for the power iteration methods. It also removes "XX" from the power iteration method names.
> Minor refactor of power iteration classes

- .gitattributes
Remove .xs files from stats. Add external as a vendored directory.
> GitHub Linguist tuning

- framework/mesh/logical_volume/rcc_logical_volume.cc
- framework/mesh/mesh_continuum/mesh_continuum.h
- framework/mesh/mesh_generator/extruder_mesh_generator.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/angle_aggregation/angle_aggregation.cc
- test/framework/tutorials/tutorial_06_wdd.cc
- test/framework/tutorials/tutorial_91a_pwld.cc
- test/framework/tutorials/tutorial_93_raytracing.cc
> No more local Vec3

- framework/math/math.cc
- framework/math/math.h
- framework/math/serial_newton_iteration/serial_newton_iteration.cc
- framework/math/serial_newton_iteration/serial_newton_iteration.h
- framework/math/spatial_discretization/cell_mappings/finite_element/piecewise_linear/piecewise_linear_base_mapping.h
- framework/math/spatial_discretization/cell_mappings/finite_element/piecewise_linear/piecewise_linear_polygon_mapping.cc
- framework/math/spatial_discretization/cell_mappings/finite_element/piecewise_linear/piecewise_linear_polyhedron_mapping.cc
- framework/math/spatial_discretization/cell_mappings/finite_element/piecewise_linear/piecewise_linear_slab_mapping.cc
- framework/math/spatial_discretization/finite_element/finite_element_data.cc
- framework/math/spatial_discretization/finite_element/finite_element_data.h
- modules/cfem_diffusion/cfem_diffusion_solver.cc
- modules/dfem_diffusion/dfem_diffusion_solver.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_adjoint_solver/lbs_adj_solver.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_adjoint_solver/lbs_adjoint.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_curvilinear_solver/lbs_curvilinear_solver.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep_chunks/cbc_sweep_chunk.h
- modules/linear_boltzmann_solvers/lbs_solver/acceleration/energy_collapse.cc
- modules/linear_boltzmann_solvers/lbs_solver/acceleration/nl_keigen_acc_context.h
- modules/linear_boltzmann_solvers/lbs_solver/acceleration/nl_keigen_acc_residual_func.cc
- modules/mg_diffusion/mg_diffusion_solver.cc
- test/framework/math/spatial_discretization/cg/sdm_test_01_continuous.cc
- test/framework/math/spatial_discretization/dg/sdm_test_01_discontinuous.cc
- test/framework/tutorials/pwlc_test1.cc
- test/framework/tutorials/pwlc_test2.cc
- test/framework/tutorials/tutorial_91a_pwld.cc
- test/framework/tutorials/tutorial_93_raytracing.cc
- test/modules/linear_boltzmann_solvers/dsa/acceleration_diffusion_cfem.cc
- test/modules/linear_boltzmann_solvers/dsa/acceleration_diffusion_dfem.cc
> `VecDbl` is expanded into `std::vector<double>`

- modules/linear_boltzmann_solvers/diffusion_dfem_solver/lbs_mip_solver.cc
- modules/linear_boltzmann_solvers/executors/pi_keigen.cc
- modules/linear_boltzmann_solvers/executors/pi_keigen_scdsa.cc
- modules/linear_boltzmann_solvers/executors/pi_keigen_smm.cc
- modules/linear_boltzmann_solvers/executors/pi_keigen_smm.h
- modules/linear_boltzmann_solvers/lbs_solver/acceleration/acceleration.cc
- modules/linear_boltzmann_solvers/lbs_solver/acceleration/acceleration.h
- modules/linear_boltzmann_solvers/lbs_solver/acceleration/diffusion.cc
- modules/linear_boltzmann_solvers/lbs_solver/acceleration/diffusion.h
- modules/linear_boltzmann_solvers/lbs_solver/acceleration/diffusion_mip_solver.cc
- modules/linear_boltzmann_solvers/lbs_solver/acceleration/diffusion_mip_solver.h
- modules/linear_boltzmann_solvers/lbs_solver/acceleration/diffusion_pwlc_solver.cc
- modules/linear_boltzmann_solvers/lbs_solver/acceleration/diffusion_pwlc_solver.h
- modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/nl_keigen_ags_solver.cc
- modules/linear_boltzmann_solvers/lbs_solver/iterative_methods/power_iteration_keigen.cc
- modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
- test/modules/linear_boltzmann_solvers/dsa/acceleration_diffusion_cfem.cc
- test/modules/linear_boltzmann_solvers/dsa/acceleration_diffusion_dfem.cc
- test/modules/linear_boltzmann_solvers/transport_keigen/c5g7/c5g7_jfnk.lua
- test/modules/linear_boltzmann_solvers/transport_keigen/c5g7/c5g7_pi.lua
- test/modules/linear_boltzmann_solvers/transport_keigen/c5g7/c5g7_pi_scdsa.lua
- test/modules/linear_boltzmann_solvers/transport_keigen/c5g7/c5g7_pi_smm.lua
- test/modules/linear_boltzmann_solvers/transport_keigen/c5g7/tests.json
This PR adds the second moment method as k-eigenvalue acceleration routine and includes a C5G7 test. The format is comparable to that of the source corrected DSA routine.
> Second Moment Method

- doc/index.rst
- doc/workflow.md
> Adding developer workflow instructions

- .mailmap
so shortlog shows the correct stats
> Updating .mailmap file

- framework/materials/multi_group_xs/multi_group_xs.cc
- framework/materials/multi_group_xs/multi_group_xs.h
- framework/materials/multi_group_xs/openmc_import.cc
- framework/materials/multi_group_xs/opensn_import.cc
- lua/framework/materials/multi_group_xs/multi_group_xs_lua_utils.cc
- test/framework/materials/tests.json
- test/framework/materials/xs_lua_printout.lua
adding chi so that it can be printed out in the console (why was it not there before?).
added the first test under `framework/materials` (I think we could use more in that folder)
@zhardy-lanl  : check the line where chi is multiplied by `ff_i`
> adding chi to xs

- modules/linear_boltzmann_solvers/lbs_solver/source_functions/source_function.cc
- modules/linear_boltzmann_solvers/response_evaluator/response_evaluator.cc
> Removed old distributed source references

- modules/linear_boltzmann_solvers/executors/pi_keigen_smm.cc
- modules/linear_boltzmann_solvers/executors/pi_keigen_smm.h
> Store K tensor as NDArray

- .github/workflows/builds.yaml
- .github/workflows/regression.yaml
- .github/workflows/weekly.yaml
- README.md
This PR does the following:
1. Allows recent node versions for GitHub actions
2. Adds a badge for weekly tests
3. Adds sanitizer tests to nightly builds
> Updating GitHub actions and badges

- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/fluds/aah_fluds_common_data.cc
The data are already in the right container with the right type
> Do not make unnecessary copies

- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/fluds/aah_fluds_common_data.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/fluds/aah_fluds_common_data.h
It is not being used by anything
> Removing `boundary_dependencies` from `AAH_FLUDSCommonData`

- framework/field_functions/interpolation/ffinter_line.cc
> Correctly size `offsets` in `FieldFunctionInterpolationLine::ExportToCSV`

- test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly_balance.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_2d_1_poly_balance_mg.lua
- test/modules/linear_boltzmann_solvers/transport_steady/transport_3d_4_cycles_1.lua
> Use correct API call for exporting field functions

- framework/data_types/ndarray.h
The version of NDArray that is currently in OpenSn was changed considerably from the original version, and several design elements that were critical to good performance were lost. This PR attempts to recover some of that performance loss.
> Refactoring NDArray for performance

- framework/data_types/ndarray.h
This is fixing a compile issue with clang-14.
> Adding missing #include

- framework/materials/multi_group_xs/multi_group_xs.cc
- framework/math/spatial_discretization/cell_mappings/finite_element/piecewise_linear/piecewise_linear_polyhedron_mapping.cc
- framework/math/spatial_discretization/cell_mappings/finite_element/piecewise_linear/piecewise_linear_polyhedron_mapping.h
- framework/math/unknown_manager/unknown_manager.cc
- framework/mesh/mesh_continuum/grid_face_histogram.cc
- framework/mesh/mesh_continuum/mesh_continuum.cc
- framework/mesh/mesh_generator/extruder_mesh_generator.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/fluds/aah_fluds_common_data.cc
- modules/point_reactor_kinetics/point_reactor_kinetics.cc
> Fixing errors found by clang sanitizer

- modules/linear_boltzmann_solvers/lbs_solver/acceleration/diffusion_mip_solver.cc
- modules/linear_boltzmann_solvers/lbs_solver/acceleration/diffusion_pwlc_solver.cc
This PR improves the assembling routines in `DiffusionPWLCSolver` and `DiffusionMIPSolver`:
- the dof map is computed just once
- the local contributions for the matrix and right-hand side vectors are accumulated into a dense matrix/vector, then added to the global matrix, vector
Impact observed on the C5G7 benchmark:
| Case | `main` | `optimized` | Speedup |
| --- | ---: | ---: | ---:|
| `DiffusionMIPSolver` | 11.189 | 5.619 | 1.9915 |
| `DiffusionPWLCSolver` | 1.422 | 0.919 | 1.5467 |
| Case | `main` | `optimized` | Speedup |
| --- | ---: | ---: | ---:|
| `DiffusionMIPSolver` | 0.170 | 0.153 | 1.1114 |
| `DiffusionPWLCSolver` | 0.238 | 0.223 | 1.0654 |
All times are in seconds.
> Improving performance of assembling routines in `DiffusionPWLCSolver` and `DiffusionMIPSolver`

- .github/workflows/builds.yaml
- CMakePresets.json
- tools/developer/ignorelist.txt
This PR along with #385 resolves issue #378.
> Adding additional checks to nightly sanitizer test

- framework/mesh/cell/cell.cc
- framework/mesh/cell/cell.h
- framework/mesh/mesh_continuum/mesh_continuum.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/fluds/aah_fluds_common_data.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/fluds/fluds_common_data.h
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/spds/spds.cc
- modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
Also renaming:
- ass_face -> adj_face_idx
- associated_face -> adj_face_idx
Closes #388
> Renaming `CellFace::GetNeighborAssociatedFace` to `CellFace::GetNeighborAdjacentFaceIndex`

- doc/coding_standard.md
> Updating coding standards for conditionals and getters/setters

- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/spds/spds.cc
> Fixing conditions that decide `FaceOrientation`

- tools/README.md
- tools/lua-input-style.md
- tools/lua-style.md
- tools/xs/CASL_2B.ipynb
- tools/xs/MGXS_README.md
- tools/xs/pincell_mgxs_openmc.ipynb
- Adding 2 more examples of MGXS generation using OpenMC
- Restructuring the `tools` folder to have `users` and `developers` subfolder
- Adding details to readme files; adding subfolder readme files.
> update to MGXS in tools

- framework/mesh/mesh_continuum/mesh_continuum.cc
- framework/mesh/mesh_continuum/mesh_continuum.h
- lua/framework/mesh/mesh_compute_vol.cc
- lua/framework/mesh/mesh_compute_vol.h
- test/framework/mesh/tests.json
- test/framework/mesh/volume_per_material.lua
Adding functionality to compute the volume of each material ID.
> computing volumes per material ID

- framework/math/quadratures/angular/product_quadrature.cc
- framework/math/spatial_discretization/finite_volume/finite_volume.cc
- framework/mesh/cell/cell.cc
- framework/mesh/cell/cell.h
- framework/mesh/mesh.cc
- framework/mesh/mesh.h
- framework/mesh/mesh_continuum/mesh_continuum.cc
- framework/mesh/mesh_continuum/mesh_continuum_global_cell_handler.cc
- framework/mesh/mesh_continuum/mesh_continuum_global_cell_handler.h
- framework/mesh/mesh_continuum/mesh_continuum_local_cell_handler.cc
- framework/mesh/mesh_continuum/mesh_continuum_local_cell_handler.h
- framework/mesh/mesh_edge_loops.h
- framework/mesh/mesh_face.h
- framework/mesh/mesh_generator/distributed_mesh_generator.cc
- framework/mesh/mesh_generator/extruder_mesh_generator.cc
- framework/mesh/mesh_generator/mesh_generator.cc
- framework/mesh/mesh_generator/split_file_mesh_generator.cc
- framework/mesh/mesh_matrix3x3.h
- framework/mesh/mesh_vector.cc
- framework/mesh/mesh_vector.h
- framework/mesh/raytrace/raytracer.cc
- framework/mesh/raytrace/raytracer.h
- framework/mesh/surface_mesh/surface_mesh.cc
- framework/mesh/surface_mesh/surface_mesh.h
- framework/mesh/unpartitioned_mesh/unpartitioned_mesh.cc
- framework/mesh/unpartitioned_mesh/unpartitioned_mesh.h
- lua/framework/mesh/surface_mesh/surface_mesh.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_curvilinear_solver/lbs_curvilinear_solver.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/fluds/aah_fluds_common_data.cc
- a first pass at cleaning up the mesh files
- removing `friend class MeshContinuum` from the  mesh_continuum_local_cell_handler
- removed unused code from `surface_mesh`
> refactoring parts of mesh

- framework/math/spatial_discretization/finite_element/piecewise_linear/piecewise_linear_continuous.cc
- framework/math/spatial_discretization/finite_element/piecewise_linear/piecewise_linear_discontinuous.cc
- framework/math/spatial_discretization/finite_volume/finite_volume.cc
- framework/math/spatial_discretization/spatial_discretization.cc
- framework/math/spatial_discretization/spatial_discretization.h
- modules/linear_boltzmann_solvers/lbs_solver/io/angular_flux_io.cc
- modules/linear_boltzmann_solvers/lbs_solver/io/flux_moments_io.cc
- modules/linear_boltzmann_solvers/lbs_solver/io/groupset_angular_flux_io.cc
- modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.cc
- modules/linear_boltzmann_solvers/lbs_solver/lbs_solver.h
> SpatialDiscretization getter for number of nodes

- doc/install_linux.md
> Fixing a typo in lua instructions for linux installation

- doc/install_linux.md
- doc/install_linux_easy.md
- doc/install_macos.md
- doc/install_macos_easy.md
- tools/configure_dependencies.py
> Correcting installation instructions

- test/modules/linear_boltzmann_solvers/transport_keigen/c5g7/materials/materials.lua
This PR will also fix the weekly tests in CI.
> Updating C5G7 tests to use new Lua input language

- framework/field_functions/interpolation/ffinter_line.h
- framework/field_functions/interpolation/ffinter_point.h
- framework/math/quadratures/angular/sldfe_sq_quadrature.h
- framework/math/spatial_discretization/cell_mappings/cell_mapping.cc
- framework/math/spatial_discretization/cell_mappings/cell_mapping.h
- framework/math/spatial_discretization/cell_mappings/finite_element/piecewise_linear/piecewise_linear_polygon_mapping.cc
- framework/math/spatial_discretization/cell_mappings/finite_element/piecewise_linear/piecewise_linear_polygon_mapping.h
- framework/math/spatial_discretization/cell_mappings/finite_element/piecewise_linear/piecewise_linear_polyhedron_mapping.h
- framework/mesh/cell/cell.cc
- framework/mesh/logical_volume/surface_mesh_logical_volume.cc
- framework/mesh/mesh.h
- framework/mesh/mesh_continuum/mesh_continuum.h
- framework/mesh/mesh_face.h
- framework/mesh/mesh_vector.cc
- framework/mesh/raytrace/raytracer.h
- framework/mesh/surface_mesh/surface_mesh.cc
- framework/mesh/surface_mesh/surface_mesh.h
- modules/diffusion/dfem_diffusion_solver.h
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/spds/spds.h
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/sweep.h
- modules/linear_boltzmann_solvers/lbs_solver/lbs_structs.h
> Fixing `#include`s in `mesh.h`

- framework/math/quadratures/angular/sldfe_sq_quadrature.cc
- framework/math/quadratures/angular/sldfe_sq_quadrature.h
- lua/lib/aquad.cc
- lua/lib/aquad.h
- lua/lib/opensn.cc
- lua/lib/parse_table.cc
- test/framework/math/quadrature/sldfesq_test.lua
- test/framework/math/quadrature/tests.json
Lua binding for SLDFESQuadrature functions. Adding creation, refinement and plotting of simplified LDFE quadrature's.
``` lua
cquad = aquad.CreateSLDFESQuadrature(0)
aquad.LocallyRefineSLDFESQ(cquad,
{x=0.5,y=-0.8,z=0.0},
45.0*math.pi/180,
false)
aquad.PrintQuadratureToFile(cquad, "TestQuad_")
```
> Lua Binding for SLDFESQ

- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/scheduler/sweep_scheduler.cc
Simplifies scheduling rules and removes unnecessary calls to AngleSetAdvance. Tested at scale.
> Simplifications to SweepScheduler

- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/communicators/aah_async_comm.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_solver/sweep/communicators/aah_async_comm.h
This PR improves the performance of AAH_ASynchronousCommunicator by enabling pre-posting of receives. Tested at scale with up to a 15% improvement in sweep performance.
> Performance improvements for AAH_ASynchronousCommunicator

- doc/devguide/index.rst
- doc/devguide/workflow.md
> adding formating instructions in developer guide

- framework/parameters/input_parameters.cc
- framework/parameters/input_parameters.h
- test/framework/parameters/params_test_01.cc
> Correcting spelling of parameter in InputParameters API

- lua/lib/opensn.cc
- modules/linear_boltzmann_solvers/response_evaluator/response_evaluator.cc
- modules/linear_boltzmann_solvers/response_evaluator/response_evaluator.h
> Bind missing `ResponseEvaluator` API into LUA layer

- .github/workflows/builds.yaml
Using our own Python install since updates to the machine keep stomping on the system install.
> Fixing coverage workflow.

- tutorials/python/lbs/first/first_example.py
> Updating Python LBS tutorial to reflect field function interface

- python/lib/xs.cc
i forgot to add code-block:: none.
sorry
> fixing documentation plain text for XS API

- doc/CMakeLists.txt
- tutorials/python/mesh/mesh_extrude.ipynb
- tutorials/python/mesh/mesh_read_gmsh_2D.ipynb
- tutorials/python/mesh/mesh_read_gmsh_3D.ipynb
- tutorials/python/xs/1g_xs_read_file.ipynb
- tutorials/python/xs/1g_xs_simple.ipynb
- tutorials/python/xs/mg_xs_read_file.ipynb
- tutorials/python/xs/mg_xs_read_openmc.ipynb
- ugly English was not caught before. sorry
- missing config file for the introduction paragraph to xs
> adding the introduction text for xs and fixing an English typo

- modules/linear_boltzmann_solvers/solvers/nl_keigen_solver.cc
- modules/linear_boltzmann_solvers/solvers/nl_keigen_solver.h
- modules/linear_boltzmann_solvers/solvers/pi_keigen_scdsa_solver.h
- modules/linear_boltzmann_solvers/solvers/pi_keigen_solver.h
- python/lib/solver.cc
- test/python/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_2d_1c_qblock_cbc.py
- test/python/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_3d_2g_exo_wedge.py
- test/python/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_3d_openmcxs_U235.py
- test/python/modules/linear_boltzmann_solvers/transport_keigen/keigenvalue_transport_3d_openmcxs_U235_smm.py
- test/python/modules/linear_boltzmann_solvers/transport_keigen/tests.json
This PR returns the eigenvalue to python.
Usage:
```
k = k_solver.GetEigenvalue()
print("k-eigenvalue =", k)
```
> returning keff to python

- framework/math/sparse_matrix/sparse_matrix.cc
- framework/math/spatial_discretization/finite_element/piecewise_linear/piecewise_linear_continuous.cc
- framework/math/spatial_discretization/finite_element/piecewise_linear/piecewise_linear_discontinuous.cc
- framework/math/unknown_manager/unknown_manager.cc
- framework/mesh/mesh_generator/split_file_mesh_generator.cc
- framework/mesh/surface_mesh/surface_mesh.cc
- framework/parameters/input_parameters.cc
- framework/runtime.cc
- framework/runtime.h
- lua/lib/console.cc
- lua/lib/opensn.cc
- modules/diffusion/mg_diffusion_solver.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_curvilinear_problem/discrete_ordinates_curvilinear_problem.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep/boundary/sweep_boundary.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep/fluds/aah_fluds.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep/fluds/aah_fluds_common_data.cc
- modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep/spds/spds.cc
- modules/linear_boltzmann_solvers/lbs_problem/lbs_problem.cc
> Removing Exit() and replacing calls to it with throw

- doc/pyapi/index.rst
- python/lib/context.cc
- python/lib/solver.cc
In this PR, the template bug of the Python interface is fixed.
Before:
After:
> Fix doc template bug

- doc/CMakeLists.txt
fix path in CMake
(We should stop using cmake to generate doc. I can't wait for lua to be gone)
> fix path in CMake

- framework/materials/multi_group_xs/multi_group_xs.cc
- framework/materials/multi_group_xs/multi_group_xs.h
- python/lib/xs.cc
- test/python/framework/materials/tests.json
- test/python/framework/materials/xs_combined.py
This binds the MultiGroupXS combining API into python. Test added.
Refs #506
> Binding `xs.Combine` to `MultiGroupXS::Initialize()`

- modules/linear_boltzmann_solvers/discrete_ordinates_problem/sweep/fluds/aah_fluds_common_data.cc
> Using adj_ instead of ass_

- README.md
- doc/source/devguide/coding_standard.rst
Update README.md. Update coding style standards allow two levels of namespace.
Closes #674
> Documentation updates

- framework/field_functions/field_function_grid_based.cc
- framework/field_functions/field_function_grid_based.h
- python/lib/fieldfunc.cc
- test/python/framework/math/spatial_discretization/cg/sdm_test_01_continuous.cc
- test/python/framework/math/spatial_discretization/dg/sdm_test_02_discontinuous.cc
- test/python/framework/tutorials/fv_test1.cc
- test/python/framework/tutorials/fv_test2.cc
- test/python/framework/tutorials/pwlc_test1.cc
- test/python/framework/tutorials/pwlc_test2.cc
- test/python/framework/tutorials/tutorial_06_wdd.cc
- test/python/framework/tutorials/tutorial_91a_pwld.cc
- test/python/framework/tutorials/tutorial_93_raytracing.cc
- test/python/modules/linear_boltzmann_solvers/dsa/acceleration_diffusion_cfem.cc
- test/python/modules/linear_boltzmann_solvers/dsa/acceleration_diffusion_dfem.cc
- test/python/modules/linear_boltzmann_solvers/transport_steady/transport_3d_5_cycles_2.py
> Changing ExportMultipleToVTK() to ExportMultipleToPVTU()

- framework/mesh/unpartitioned_mesh/unpartitioned_mesh.cc
> Fixing face neighbor assignment for boundary cells on unstructured meshes

- tools/scaling/sweep/node_to_node/unstructured_mesh/strong/generate_scaling_study.py
- tools/scaling/sweep/node_to_node/unstructured_mesh/strong/strong_scaling.py
- tools/scaling/sweep/node_to_node/unstructured_mesh/weak/generate_scaling_study.py
- tools/scaling/sweep/node_to_node/unstructured_mesh/weak/weak_scaling.py
> Updating scaling study scripts and inputs

- python/lib/fieldfunc.cc
- python/lib/response.cc
- python/lib/solver.cc
> Finalizing Python binding documentation

- modules/linear_boltzmann_solvers/lbs_problem/lbs_problem.cc
> Removing "spatial_discretization" parameter from `LBSProblem::GetOptionsBlock`

- modules/linear_boltzmann_solvers/lbs_problem/source_functions/source_function.cc
- modules/linear_boltzmann_solvers/lbs_problem/source_functions/source_function.h
- modules/linear_boltzmann_solvers/lbs_problem/source_functions/transient_source_function.cc
- modules/linear_boltzmann_solvers/lbs_problem/source_functions/transient_source_function.h
> Refactoring inside `SourceFunction`

- framework/math/quadratures/angular/lebedev_quadrature.cc
- test/python/modules/linear_boltzmann_solvers/transport_steady/tests.json
- test/python/modules/linear_boltzmann_solvers/transport_steady/transport_3d_7a_leb_quad.py
- test/python/modules/linear_boltzmann_solvers/transport_steady/transport_3d_7b_leb_quad.py
M2D and D2M matrices should now be generated properly when Lebedev Quadrature is called. 
Additionally, two python tests were added that now use the corrected Lebedev Quadrature.
> Update to fix Lebedev Generation.

- framework/materials/multi_group_xs/multi_group_xs.cc
- framework/materials/multi_group_xs/multi_group_xs.h
- framework/materials/multi_group_xs/openmc_import.cc
- framework/materials/multi_group_xs/xsfile.h
- modules/linear_boltzmann_solvers/lbs_problem/lbs_problem.cc
- modules/linear_boltzmann_solvers/lbs_problem/lbs_problem.h
> Scattering order is stored as `unsigned int`
